version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - "3000:3000"
      - "80:80"
      - "443:443"
    volumes:
      - .:/app
      - /app/node_modules
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt/live/projeto-compras-dsm.duckdns.org/fullchain.pem:/etc/nginx/certs/fullchain.pem:ro
      - /etc/letsencrypt/live/projeto-compras-dsm.duckdns.org/privkey.pem:/etc/nginx/certs/privkey.pem:ro
    environment:
      - NEXT_PUBLIC_API_BASEURL=${NEXT_PUBLIC_API_BASEURL}
    networks:
      - rede_compras

  # #backend
  # back_end:
  #   image: 
  #   build:
  #     context: 
  #     dockerfile: Dockerfile
  #   container_name: back_end
  #   environment:
  #     
  #   depends_on:
  #     - mongo
  #   ports:
  #     - "4000:4000"
  #   networks:
  #     - rede_compras

networks:
  rede_compras:
    driver: bridge
